/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BonusType = IDL.Variant({
  'signup' : IDL.Null,
  'depositMatch' : IDL.Null,
  'loyalty' : IDL.Null,
});
export const Time = IDL.Int;
export const Bonus = IDL.Record({
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'bonusType' : BonusType,
  'timestamp' : Time,
  'amount' : IDL.Float64,
  'bonusId' : IDL.Nat,
});
export const DepositStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const DepositRequest = IDL.Record({
  'status' : DepositStatus,
  'mpesaReference' : IDL.Opt(IDL.Text),
  'requestId' : IDL.Nat,
  'user' : IDL.Principal,
  'adminNote' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TradeStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const ForexPair = IDL.Record({
  'baseCurrency' : IDL.Text,
  'quoteCurrency' : IDL.Text,
  'symbol' : IDL.Text,
});
export const TradeDirection = IDL.Variant({
  'buy' : IDL.Null,
  'sell' : IDL.Null,
});
export const TradePosition = IDL.Record({
  'status' : TradeStatus,
  'forexPair' : ForexPair,
  'direction' : TradeDirection,
  'leverage' : IDL.Nat,
  'platformFee' : IDL.Float64,
  'openPrice' : IDL.Float64,
  'closeTimestamp' : IDL.Opt(Time),
  'user' : IDL.Principal,
  'profitLoss' : IDL.Opt(IDL.Float64),
  'tradeId' : IDL.Nat,
  'closePrice' : IDL.Opt(IDL.Float64),
  'margin' : IDL.Float64,
  'openTimestamp' : Time,
});
export const TradingFee = IDL.Record({
  'user' : IDL.Principal,
  'tradeId' : IDL.Nat,
  'timestamp' : Time,
  'amount' : IDL.Float64,
  'feeId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'role' : UserRole,
  'walletBalance' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyBonus' : IDL.Func(
      [IDL.Principal, IDL.Float64, BonusType, IDL.Text],
      [Bonus],
      [],
    ),
  'approveDeposit' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text)],
      [DepositRequest],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeTrade' : IDL.Func([IDL.Nat], [TradePosition], []),
  'depositFunds' : IDL.Func(
      [IDL.Float64, IDL.Opt(IDL.Text)],
      [DepositRequest],
      [],
    ),
  'getAllBonuses' : IDL.Func([], [IDL.Vec(Bonus)], ['query']),
  'getAllDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getAllTrades' : IDL.Func([], [IDL.Vec(TradePosition)], ['query']),
  'getAllTradingFees' : IDL.Func([], [IDL.Vec(TradingFee)], ['query']),
  'getAvailableBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepositStatus' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getMpesaNumber' : IDL.Func([], [IDL.Text], ['query']),
  'getOpenTrades' : IDL.Func([], [IDL.Vec(TradePosition)], ['query']),
  'getPlatformRevenue' : IDL.Func([], [IDL.Float64], ['query']),
  'getTradeHistory' : IDL.Func([], [IDL.Vec(TradePosition)], ['query']),
  'getTradingFees' : IDL.Func([], [IDL.Vec(TradingFee)], ['query']),
  'getUserBonuses' : IDL.Func([], [IDL.Vec(Bonus)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'openTrade' : IDL.Func(
      [IDL.Text, TradeDirection, IDL.Nat, IDL.Float64],
      [TradePosition],
      [],
    ),
  'rejectDeposit' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text)],
      [DepositRequest],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMpesaNumber' : IDL.Func([IDL.Text], [], []),
  'submitTradingFee' : IDL.Func([IDL.Nat, IDL.Float64], [TradingFee], []),
  'withdrawFunds' : IDL.Func([IDL.Float64], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BonusType = IDL.Variant({
    'signup' : IDL.Null,
    'depositMatch' : IDL.Null,
    'loyalty' : IDL.Null,
  });
  const Time = IDL.Int;
  const Bonus = IDL.Record({
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'bonusType' : BonusType,
    'timestamp' : Time,
    'amount' : IDL.Float64,
    'bonusId' : IDL.Nat,
  });
  const DepositStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const DepositRequest = IDL.Record({
    'status' : DepositStatus,
    'mpesaReference' : IDL.Opt(IDL.Text),
    'requestId' : IDL.Nat,
    'user' : IDL.Principal,
    'adminNote' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TradeStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const ForexPair = IDL.Record({
    'baseCurrency' : IDL.Text,
    'quoteCurrency' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const TradeDirection = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const TradePosition = IDL.Record({
    'status' : TradeStatus,
    'forexPair' : ForexPair,
    'direction' : TradeDirection,
    'leverage' : IDL.Nat,
    'platformFee' : IDL.Float64,
    'openPrice' : IDL.Float64,
    'closeTimestamp' : IDL.Opt(Time),
    'user' : IDL.Principal,
    'profitLoss' : IDL.Opt(IDL.Float64),
    'tradeId' : IDL.Nat,
    'closePrice' : IDL.Opt(IDL.Float64),
    'margin' : IDL.Float64,
    'openTimestamp' : Time,
  });
  const TradingFee = IDL.Record({
    'user' : IDL.Principal,
    'tradeId' : IDL.Nat,
    'timestamp' : Time,
    'amount' : IDL.Float64,
    'feeId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'role' : UserRole,
    'walletBalance' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyBonus' : IDL.Func(
        [IDL.Principal, IDL.Float64, BonusType, IDL.Text],
        [Bonus],
        [],
      ),
    'approveDeposit' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text)],
        [DepositRequest],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeTrade' : IDL.Func([IDL.Nat], [TradePosition], []),
    'depositFunds' : IDL.Func(
        [IDL.Float64, IDL.Opt(IDL.Text)],
        [DepositRequest],
        [],
      ),
    'getAllBonuses' : IDL.Func([], [IDL.Vec(Bonus)], ['query']),
    'getAllDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getAllTrades' : IDL.Func([], [IDL.Vec(TradePosition)], ['query']),
    'getAllTradingFees' : IDL.Func([], [IDL.Vec(TradingFee)], ['query']),
    'getAvailableBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepositStatus' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
    'getMpesaNumber' : IDL.Func([], [IDL.Text], ['query']),
    'getOpenTrades' : IDL.Func([], [IDL.Vec(TradePosition)], ['query']),
    'getPlatformRevenue' : IDL.Func([], [IDL.Float64], ['query']),
    'getTradeHistory' : IDL.Func([], [IDL.Vec(TradePosition)], ['query']),
    'getTradingFees' : IDL.Func([], [IDL.Vec(TradingFee)], ['query']),
    'getUserBonuses' : IDL.Func([], [IDL.Vec(Bonus)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'openTrade' : IDL.Func(
        [IDL.Text, TradeDirection, IDL.Nat, IDL.Float64],
        [TradePosition],
        [],
      ),
    'rejectDeposit' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text)],
        [DepositRequest],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMpesaNumber' : IDL.Func([IDL.Text], [], []),
    'submitTradingFee' : IDL.Func([IDL.Nat, IDL.Float64], [TradingFee], []),
    'withdrawFunds' : IDL.Func([IDL.Float64], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };