/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bonus {
  'user' : Principal,
  'description' : string,
  'isActive' : boolean,
  'bonusType' : BonusType,
  'timestamp' : Time,
  'amount' : number,
  'bonusId' : bigint,
}
export type BonusType = { 'signup' : null } |
  { 'depositMatch' : null } |
  { 'loyalty' : null };
export interface DepositRequest {
  'status' : DepositStatus,
  'mpesaReference' : [] | [string],
  'requestId' : bigint,
  'user' : Principal,
  'adminNote' : [] | [string],
  'timestamp' : Time,
  'amount' : number,
}
export type DepositStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ForexPair {
  'baseCurrency' : string,
  'quoteCurrency' : string,
  'symbol' : string,
}
export type Time = bigint;
export type TradeDirection = { 'buy' : null } |
  { 'sell' : null };
export interface TradePosition {
  'status' : TradeStatus,
  'forexPair' : ForexPair,
  'direction' : TradeDirection,
  'leverage' : bigint,
  'platformFee' : number,
  'openPrice' : number,
  'closeTimestamp' : [] | [Time],
  'user' : Principal,
  'profitLoss' : [] | [number],
  'tradeId' : bigint,
  'closePrice' : [] | [number],
  'margin' : number,
  'openTimestamp' : Time,
}
export type TradeStatus = { 'closed' : null } |
  { 'open' : null };
export interface TradingFee {
  'user' : Principal,
  'tradeId' : bigint,
  'timestamp' : Time,
  'amount' : number,
  'feeId' : bigint,
}
export interface UserProfile {
  'displayName' : string,
  'role' : UserRole,
  'walletBalance' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyBonus' : ActorMethod<[Principal, number, BonusType, string], Bonus>,
  'approveDeposit' : ActorMethod<[bigint, [] | [string]], DepositRequest>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeTrade' : ActorMethod<[bigint], TradePosition>,
  'depositFunds' : ActorMethod<[number, [] | [string]], DepositRequest>,
  'getAllBonuses' : ActorMethod<[], Array<Bonus>>,
  'getAllDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getAllTrades' : ActorMethod<[], Array<TradePosition>>,
  'getAllTradingFees' : ActorMethod<[], Array<TradingFee>>,
  'getAvailableBalance' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDepositStatus' : ActorMethod<[], Array<DepositRequest>>,
  'getMpesaNumber' : ActorMethod<[], string>,
  'getOpenTrades' : ActorMethod<[], Array<TradePosition>>,
  'getPlatformRevenue' : ActorMethod<[], number>,
  'getTradeHistory' : ActorMethod<[], Array<TradePosition>>,
  'getTradingFees' : ActorMethod<[], Array<TradingFee>>,
  'getUserBonuses' : ActorMethod<[], Array<Bonus>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'openTrade' : ActorMethod<
    [string, TradeDirection, bigint, number],
    TradePosition
  >,
  'rejectDeposit' : ActorMethod<[bigint, [] | [string]], DepositRequest>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMpesaNumber' : ActorMethod<[string], undefined>,
  'submitTradingFee' : ActorMethod<[bigint, number], TradingFee>,
  'withdrawFunds' : ActorMethod<[number], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];