/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TradePosition {
    status: TradeStatus;
    forexPair: ForexPair;
    direction: TradeDirection;
    leverage: bigint;
    platformFee: number;
    openPrice: number;
    closeTimestamp?: Time;
    user: Principal;
    profitLoss?: number;
    tradeId: bigint;
    closePrice?: number;
    margin: number;
    openTimestamp: Time;
}
export type Time = bigint;
export interface ForexPair {
    baseCurrency: string;
    quoteCurrency: string;
    symbol: string;
}
export interface DepositRequest {
    status: DepositStatus;
    mpesaReference?: string;
    requestId: bigint;
    user: Principal;
    adminNote?: string;
    timestamp: Time;
    amount: number;
}
export interface Bonus {
    user: Principal;
    description: string;
    isActive: boolean;
    bonusType: BonusType;
    timestamp: Time;
    amount: number;
    bonusId: bigint;
}
export interface TradingFee {
    user: Principal;
    tradeId: bigint;
    timestamp: Time;
    amount: number;
    feeId: bigint;
}
export interface UserProfile {
    displayName: string;
    role: UserRole;
    walletBalance: number;
}
export enum BonusType {
    signup = "signup",
    depositMatch = "depositMatch",
    loyalty = "loyalty"
}
export enum DepositStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum TradeDirection {
    buy = "buy",
    sell = "sell"
}
export enum TradeStatus {
    closed = "closed",
    open = "open"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    applyBonus(targetUser: Principal, amount: number, bonusType: BonusType, description: string): Promise<Bonus>;
    approveDeposit(requestId: bigint, adminNote: string | null): Promise<DepositRequest>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    closeTrade(tradeId: bigint): Promise<TradePosition>;
    depositFunds(amount: number, mpesaRef: string | null): Promise<DepositRequest>;
    getAllBonuses(): Promise<Array<Bonus>>;
    getAllDepositRequests(): Promise<Array<DepositRequest>>;
    getAllTrades(): Promise<Array<TradePosition>>;
    getAllTradingFees(): Promise<Array<TradingFee>>;
    getAvailableBalance(): Promise<number>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDepositStatus(): Promise<Array<DepositRequest>>;
    getMpesaNumber(): Promise<string>;
    getOpenTrades(): Promise<Array<TradePosition>>;
    getPlatformRevenue(): Promise<number>;
    getTradeHistory(): Promise<Array<TradePosition>>;
    getTradingFees(): Promise<Array<TradingFee>>;
    getUserBonuses(): Promise<Array<Bonus>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    openTrade(pairSymbol: string, direction: TradeDirection, leverage: bigint, margin: number): Promise<TradePosition>;
    rejectDeposit(requestId: bigint, adminNote: string | null): Promise<DepositRequest>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setMpesaNumber(newNumber: string): Promise<void>;
    submitTradingFee(tradeId: bigint, amount: number): Promise<TradingFee>;
    withdrawFunds(amount: number): Promise<boolean>;
}
import type { Bonus as _Bonus, BonusType as _BonusType, DepositRequest as _DepositRequest, DepositStatus as _DepositStatus, ForexPair as _ForexPair, Time as _Time, TradeDirection as _TradeDirection, TradePosition as _TradePosition, TradeStatus as _TradeStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async applyBonus(arg0: Principal, arg1: number, arg2: BonusType, arg3: string): Promise<Bonus> {
        if (this.processError) {
            try {
                const result = await this.actor.applyBonus(arg0, arg1, to_candid_BonusType_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_Bonus_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyBonus(arg0, arg1, to_candid_BonusType_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_Bonus_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveDeposit(arg0: bigint, arg1: string | null): Promise<DepositRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDeposit(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_DepositRequest_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDeposit(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_DepositRequest_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async closeTrade(arg0: bigint): Promise<TradePosition> {
        if (this.processError) {
            try {
                const result = await this.actor.closeTrade(arg0);
                return from_candid_TradePosition_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeTrade(arg0);
            return from_candid_TradePosition_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async depositFunds(arg0: number, arg1: string | null): Promise<DepositRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.depositFunds(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_DepositRequest_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.depositFunds(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_DepositRequest_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBonuses(): Promise<Array<Bonus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBonuses();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBonuses();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDepositRequests(): Promise<Array<DepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDepositRequests();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDepositRequests();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrades(): Promise<Array<TradePosition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrades();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrades();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTradingFees(): Promise<Array<TradingFee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTradingFees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTradingFees();
            return result;
        }
    }
    async getAvailableBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableBalance();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDepositStatus(): Promise<Array<DepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepositStatus();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepositStatus();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMpesaNumber(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMpesaNumber();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMpesaNumber();
            return result;
        }
    }
    async getOpenTrades(): Promise<Array<TradePosition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenTrades();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenTrades();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformRevenue(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformRevenue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformRevenue();
            return result;
        }
    }
    async getTradeHistory(): Promise<Array<TradePosition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeHistory();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeHistory();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradingFees(): Promise<Array<TradingFee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradingFees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradingFees();
            return result;
        }
    }
    async getUserBonuses(): Promise<Array<Bonus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBonuses();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBonuses();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async openTrade(arg0: string, arg1: TradeDirection, arg2: bigint, arg3: number): Promise<TradePosition> {
        if (this.processError) {
            try {
                const result = await this.actor.openTrade(arg0, to_candid_TradeDirection_n31(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_TradePosition_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.openTrade(arg0, to_candid_TradeDirection_n31(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_TradePosition_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectDeposit(arg0: bigint, arg1: string | null): Promise<DepositRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDeposit(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_DepositRequest_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDeposit(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_DepositRequest_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setMpesaNumber(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMpesaNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMpesaNumber(arg0);
            return result;
        }
    }
    async submitTradingFee(arg0: bigint, arg1: number): Promise<TradingFee> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTradingFee(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTradingFee(arg0, arg1);
            return result;
        }
    }
    async withdrawFunds(arg0: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawFunds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawFunds(arg0);
            return result;
        }
    }
}
function from_candid_BonusType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BonusType): BonusType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Bonus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bonus): Bonus {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_DepositRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositRequest): DepositRequest {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DepositStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositStatus): DepositStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TradeDirection_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeDirection): TradeDirection {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TradePosition_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradePosition): TradePosition {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TradeStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeStatus): TradeStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TradeStatus;
    forexPair: _ForexPair;
    direction: _TradeDirection;
    leverage: bigint;
    platformFee: number;
    openPrice: number;
    closeTimestamp: [] | [_Time];
    user: Principal;
    profitLoss: [] | [number];
    tradeId: bigint;
    closePrice: [] | [number];
    margin: number;
    openTimestamp: _Time;
}): {
    status: TradeStatus;
    forexPair: ForexPair;
    direction: TradeDirection;
    leverage: bigint;
    platformFee: number;
    openPrice: number;
    closeTimestamp?: Time;
    user: Principal;
    profitLoss?: number;
    tradeId: bigint;
    closePrice?: number;
    margin: number;
    openTimestamp: Time;
} {
    return {
        status: from_candid_TradeStatus_n17(_uploadFile, _downloadFile, value.status),
        forexPair: value.forexPair,
        direction: from_candid_TradeDirection_n19(_uploadFile, _downloadFile, value.direction),
        leverage: value.leverage,
        platformFee: value.platformFee,
        openPrice: value.openPrice,
        closeTimestamp: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.closeTimestamp)),
        user: value.user,
        profitLoss: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.profitLoss)),
        tradeId: value.tradeId,
        closePrice: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.closePrice)),
        margin: value.margin,
        openTimestamp: value.openTimestamp
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    role: _UserRole;
    walletBalance: number;
}): {
    displayName: string;
    role: UserRole;
    walletBalance: number;
} {
    return {
        displayName: value.displayName,
        role: from_candid_UserRole_n29(_uploadFile, _downloadFile, value.role),
        walletBalance: value.walletBalance
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    description: string;
    isActive: boolean;
    bonusType: _BonusType;
    timestamp: _Time;
    amount: number;
    bonusId: bigint;
}): {
    user: Principal;
    description: string;
    isActive: boolean;
    bonusType: BonusType;
    timestamp: Time;
    amount: number;
    bonusId: bigint;
} {
    return {
        user: value.user,
        description: value.description,
        isActive: value.isActive,
        bonusType: from_candid_BonusType_n5(_uploadFile, _downloadFile, value.bonusType),
        timestamp: value.timestamp,
        amount: value.amount,
        bonusId: value.bonusId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _DepositStatus;
    mpesaReference: [] | [string];
    requestId: bigint;
    user: Principal;
    adminNote: [] | [string];
    timestamp: _Time;
    amount: number;
}): {
    status: DepositStatus;
    mpesaReference?: string;
    requestId: bigint;
    user: Principal;
    adminNote?: string;
    timestamp: Time;
    amount: number;
} {
    return {
        status: from_candid_DepositStatus_n10(_uploadFile, _downloadFile, value.status),
        mpesaReference: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.mpesaReference)),
        requestId: value.requestId,
        user: value.user,
        adminNote: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.adminNote)),
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): DepositStatus {
    return "pending" in value ? DepositStatus.pending : "approved" in value ? DepositStatus.approved : "rejected" in value ? DepositStatus.rejected : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
}): TradeStatus {
    return "closed" in value ? TradeStatus.closed : "open" in value ? TradeStatus.open : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradeDirection {
    return "buy" in value ? TradeDirection.buy : "sell" in value ? TradeDirection.sell : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    signup: null;
} | {
    depositMatch: null;
} | {
    loyalty: null;
}): BonusType {
    return "signup" in value ? BonusType.signup : "depositMatch" in value ? BonusType.depositMatch : "loyalty" in value ? BonusType.loyalty : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bonus>): Array<Bonus> {
    return value.map((x)=>from_candid_Bonus_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DepositRequest>): Array<DepositRequest> {
    return value.map((x)=>from_candid_DepositRequest_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradePosition>): Array<TradePosition> {
    return value.map((x)=>from_candid_TradePosition_n15(_uploadFile, _downloadFile, x));
}
function to_candid_BonusType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BonusType): _BonusType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TradeDirection_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirection): _TradeDirection {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    role: UserRole;
    walletBalance: number;
}): {
    displayName: string;
    role: _UserRole;
    walletBalance: number;
} {
    return {
        displayName: value.displayName,
        role: to_candid_UserRole_n13(_uploadFile, _downloadFile, value.role),
        walletBalance: value.walletBalance
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BonusType): {
    signup: null;
} | {
    depositMatch: null;
} | {
    loyalty: null;
} {
    return value == BonusType.signup ? {
        signup: null
    } : value == BonusType.depositMatch ? {
        depositMatch: null
    } : value == BonusType.loyalty ? {
        loyalty: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirection): {
    buy: null;
} | {
    sell: null;
} {
    return value == TradeDirection.buy ? {
        buy: null
    } : value == TradeDirection.sell ? {
        sell: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
